[package]
name = "json_sample_shared"
version = "0.1.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]
license = "MIT/Apache-2.0"

[dependencies]
quote = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = { version = "0.9", features = ["preserve_order"] }
reqwest = "0.4"
