[package]
name = "derive-swagger-2"
version = "0.1.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]

[dependencies]
syn = "0.10"
quote = "0.3"
serde = "0.8"
serde_json = "0.8"
hyper = { version = "0.9", default-features = false, features = ["security-framework"] }

[lib]
proc-macro = true
