[package]
name = "json_typegen_shared"
version = "0.1.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]
license = "MIT/Apache-2.0"
description = "Codegen from JSON samples. Not intended to be used directly. See repository for the intended crates."
homepage = "https://github.com/evestera/json_typegen"
repository = "https://github.com/evestera/json_typegen"
documentation = "https://docs.rs/json_typegen_shared"
readme = "README.md"

[features]
unstable = []
default = ["remote-samples", "local-samples"]
remote-samples = ["reqwest"]
local-samples = []

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = { version = "0.9", features = ["preserve_order"] }
reqwest = { version = "0.4", optional = true }
error-chain = "0.10"
lazy_static = "0.2"
linked-hash-map = { version = "0.4.1" }
Inflector = "0.10"
regex = "0.2"
syn = { version = "0.11", features = ["full", "parsing"] }
synom = "*"
unindent = "0.1.2"
