[package]
name = "json_typegen_demo"
version = "0.2.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]
license = "MIT/Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = "0.9"
serde_json = "0.9"
# json_typegen = "0.2"
json_typegen = { path = "../json_typegen", version = "0.2" }